import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { Canvas } from "@react-three/fiber";
import { Floor } from '../components/Floor';
import { Box } from '../components/Box';
import { LightBulb } from '../components/LightBulb';
import OrbitControls from '../components/OrbitControls';

const Home: NextPage = () => {
  return (
    <div className={styles.scene}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Canvas
          shadows={true}
          className={styles.canvas}
          camera={{
            position: [-6, 7, 7],
          }}
        >
        <ambientLight color={"white"} intensity={0.3} />
        <LightBulb position={[0, 3, 0]} />
        <Box rotateX={3} rotateY={0.2} />
        <Floor position={[0, -1, 0]} />

        <OrbitControls />
      </Canvas>
    </div>
  )
}

export default Home
